# Generated by Django 2.2 on 2019-05-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0002_auto_20190503_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic_id_2st',
            new_name='topic_id_2nd',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic_id_3st',
            new_name='topic_id_3rd',
        ),
    ]
