# Generated by Django 2.2 on 2019-05-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0003_auto_20190506_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic_id_2nd',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic_id_3rd',
        ),
    ]
